require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Durable, database-backed jobs. Start a worker with bin/jobs (or use bin/dev).
  config.active_job.queue_adapter = :solid_queue

  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # no-store for everything under public/, and set OUTSIDE the caching toggle
  # below so it always applies.
  #
  # public/ serves super-pixel.js, and a cached pixel is a pixel you cannot
  # iterate on: an edit appears to do nothing until the browser decides to
  # revalidate. Rails' generated setting for this sits inside the
  # `caching-dev.txt` branch, so by default NO cache header is sent at all and
  # browsers fall back to heuristic caching off Last-Modified - which is how a
  # fixed pixel kept behaving like the broken one for long enough to be
  # thoroughly confusing.
  config.public_file_server.headers = { "cache-control" => "no-store" }

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Don't care if the mailer can't send.

  # Disable caching for Action Mailer templates even if Action Controller
  # caching is enabled.


  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
